#!/usr/bin/env bash

set -e

/usr/libexec/PlistBuddy \
  -c 'Add :UIStatusBarHidden bool true' \
  "platforms/ios/Tic Tac Yo/Tic Tac Yo-Info.plist"

/usr/libexec/PlistBuddy \
  -c 'Add :UIViewControllerBasedStatusBarAppearance bool false' \
  "platforms/ios/Tic Tac Yo/Tic Tac Yo-Info.plist"
